### ISSUE TITLE
✨ [Feat] - POST image 요청 처리

### ISSUE THREAD

**Issue by yes-ee** [web42serv/webserv#5]
## 📝 Description
HTTP `POST` 요청으로 `이미지`가 들어왔을 때 처리하기

## ✅ To-do
- [x] 파이썬 스크립트 수정

## 📚 Etc
- 특이사항

**Comment by ohhamma** [comment]
이 링크를 참고해봅시당 ~~!
https://www.tutorialspoint.com/How-do-we-do-a-file-upload-using-Python-CGI-Programming

**Comment by chobinee** [comment]
특이사항 : 윤주 거

**Comment by ohhamma** [comment]
특이사항 : 결국 내가 해결 못함 ㅜ.ㅜ
