### ISSUE TITLE
🐞 [Bug] - 잘못된 cgi 파일에 대한 오류

### ISSUE THREAD

**Issue by yes-ee** [web42serv/webserv#8]
## 🕵🏻 Condition
- cgi 파일이 제대로 실행이 안 되는 경우에도 클라이언트에게 status code 200 반환

## 📝 Description
- 상황에 맞게 404 등 에러 status code 설정 필요

## ✅ To-do
- [x] 오류 발생 시 response에 알맞은 status code 설정

## 📚 Etc
- 특이사항

**Comment by ohhamma** [comment]
http status code 관련 자료입니다. 참고하시면 좋을 것 같습니다.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
